name: Build & Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      #- name: Install dependencies
      #  run: pip install pymongo
      
      #- name: Unit tests
      #  run: python -m unittest discover -s test

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: dominik9917/dp-analyzer
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
    - name: Executing remote ssh docker deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SSH_KEY_PASS }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/datalake_infrastructure/production_infrastructure
          docker-compose pull analyzer && docker-compose up -d --no-deps --build analyzer && docker system prune -f
